_extends: .github
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: $MAJOR.$MINOR.$PATCH

template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: enhancement'
  patch:
    labels:
      - 'type: bug'
      - 'type: chore'
      - 'type: refactor'
      - 'type: documentation'
      - 'type: dependencies'
      - 'type: security'
